export const RequirementKeys = {
  GENERAL_SKILLS: 'General Skills',
  COMMUNICATION_SKILLS: 'Communication Skills',
  LEADERSHIP: 'Leadership',
  TEAMWORK: 'Teamwork',
  PROBLEM_SOLVING: 'Problem Solving',
  TIME_MANAGEMENT: 'Time Management',
  SPECIFIC_SKILLS: 'Specific Skills',
  EVENT_PLANNING: 'Event Planning',
  FUNDRAISING: 'Fundraising',
  MARKETING: 'Marketing',
  SOCIAL_MEDIA_MANAGEMENT: 'Social Media Management',
  PUBLIC_SPEAKING: 'Public Speaking',
  PROJECT_MANAGEMENT: 'Project Management',
  DATA_ENTRY: 'Data Entry',
  RESEARCH_SKILLS: 'Research Skills',
  CUSTOMER_SERVICE: 'Customer Service',
  'TEACHING/TUTORING': 'Teaching/Tutoring',
  TECHNICAL_SKILLS: 'Technical Skills',
  GRAPHIC_DESIGN: 'Graphic Design',
  WEB_DEVELOPMENT: 'Web Development',
  PHOTOGRAPHY: 'Photography',
  VIDEO_EDITING: 'Video Editing',
  IT_SUPPORT: 'IT Support',
  DATA_ANALYSIS: 'Data Analysis',
  SOCIAL_MEDIA_ADVERTISING: 'Social Media Advertising',
  HEALTH_AND_SAFETY_SKILLS: 'Health and Safety Skills',
  'FIRST_AID/CPR_CERTIFICATION': 'First Aid/CPR Certification',
  SAFETY_TRAINING: 'Safety Training',
  'COUNSELING/SUPPORT_SKILLS': 'Counseling/Support Skills',
  MENTAL_HEALTH_AWARENESS: 'Mental Health Awareness',
  CREATIVE_SKILLS: 'Creative Skills',
  ARTISTIC_SKILLS: 'Artistic Skills',
  WRITING: 'Writing',
  MUSIC: 'Music (instrumental and vocal skills)',
  ENVIRONMENTAL_SKILLS: 'Environmental Skills',
  'GARDENING/AGRICULTURE': 'Gardening/Agriculture',
  CONSERVATION_AWARENESS: 'Conservation Awareness',
  WASTE_MANAGEMENT: 'Waste Management',
} as const;

export const RequirementsSkills = {
  GENERAL_SKILLS: [
    'COMMUNICATION_SKILLS',
    'LEADERSHIP',
    'TEAMWORK',
    'PROBLEM_SOLVING',
    'TIME_MANAGEMENT',
  ],
  SPECIFIC_SKILLS: [
    'EVENT_PLANNING',
    'FUNDRAISING',
    'MARKETING',
    'SOCIAL_MEDIA_MANAGEMENT',
    'PUBLIC_SPEAKING',
    'PROJECT_MANAGEMENT',
    'DATA_ENTRY',
    'RESEARCH_SKILLS',
    'CUSTOMER_SERVICE',
    'TEACHING/TUTORING',
  ],
  TECHNICAL_SKILLS: [
    'GRAPHIC_DESIGN',
    'WEB_DEVELOPMENT',
    'PHOTOGRAPHY',
    'VIDEO_EDITING',
    'IT_SUPPORT',
    'DATA_ANALYSIS',
    'SOCIAL_MEDIA_ADVERTISING',
  ],
  HEALTH_AND_SAFETY_SKILLS: [
    'FIRST_AID/CPR_CERTIFICATION',
    'SAFETY_TRAINING',
    'COUNSELING/SUPPORT_SKILLS',
    'MENTAL_HEALTH_AWARENESS',
  ],
  CREATIVE_SKILLS: ['ARTISTIC_SKILLS', 'WRITING', 'MUSIC'],
  ENVIRONMENTAL_SKILLS: ['GARDENING/AGRICULTURE', 'CONSERVATION_AWARENESS', 'WASTE_MANAGEMENT'],
} as const;
