name: CD
on: 
  push:
    branches: [ feature/config_nginx_to_host_app ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: tranhungkt/app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull tranhungkt/app:latest
      - name: Delete old container
        run: docker rm -f engage-together-container
      - name: Run docker container
        run: docker run -d -p 3000:80 --name engage-together-container tranhungkt/app