name: CD
on: 
  push:
    branches: [ feature/setup_git_actions ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install 

      - name: build
        run: npm run build
